### PR TITLE
Check that OCSP producedAt is later than TimeStamp

### PR DESCRIPTION
**Pull request by metsma**
IB-5988

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by moll** [comment]
What's the reasoning behind this change? The comment above the code refers to XAdES Baseline Profile v2.1.1's Section 8, but I can't spot requirements for the time relation between OCSP responses and timestamps. Are the requirements hidden somewhere else?

**Comment by Counter178** [comment]
> What's the reasoning behind this change? The comment above the code refers to XAdES Baseline Profile v2.1.1's Section 8, but I can't spot requirements for the time relation between OCSP responses and timestamps. Are the requirements hidden somewhere else?

For T-Level, the changes were made in order TS would check creation be first before OCSP. Unfortunately XAdES Baseline Profile v2.1.1 doesn't explain that requirement.

**Comment by moll** [comment]
@Counter178, that doesn't explain _why_ the change in the first place. ;) If it's not a requirement of XAdES, forcing validation won't be particularly standards compliant.

**Comment by Counter178** [comment]
> @Counter178, that doesn't explain _why_ the change in the first place. ;) If it's not a requirement of XAdES, forcing validation won't be particularly standards compliant.

As far as I know, there isn't any line for not doing it. If I increase security measures in order, to validate documentations better, then that doesn't mean it's not compliant. No other sentence describes the line. Also XAdES doesn't define TS that much than Bdoc documentations itself.

**Pull request merged**
