### PR TITLE
Update API to fIx build

### LINKED ISSUE #371: build error: no matching function for call to ‘push_back(digidoc::Container*...
I am having some trouble building from master and I am not sure where this one comes from?

Can someone help?

```sh
[  1%] Built target docs
[ 40%] Built target digidocpp_priv
[ 45%] Built target minizip
[ 46%] Building CXX object src/CMakeFiles/digidocpp.dir/Container.cpp.o
/home/hector/git/libdigidocpp/src/Container.cpp: In instantiation of ‘static void digidoc::Container::addContainerImplementation() [with T = digidoc::PDF]’:
/home/hector/git/libdigidocpp/src/Container.cpp:158:48:   required from here
/home/hector/git/libdigidocpp/src/Container.cpp:423:27: error: no matching function for call to ‘push_back(digidoc::Container* (*)(const string&))’
  423 |     m_createList.push_back(&T::createInternal);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/vector:67,
                 from /home/hector/git/libdigidocpp/src/Container.h:26,
                 from /home/hector/git/libdigidocpp/src/Container.cpp:20:
/usr/include/c++/10/bits/stl_vector.h:1187:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&); _Alloc = std::allocator<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)]’ (near match)
 1187 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/usr/include/c++/10/bits/stl_vector.h:1187:7: note:   conversion of argument 1 would be ill-formed:
/home/hector/git/libdigidocpp/src/Container.cpp:423:27: error: invalid conversion from ‘digidoc::Container* (*)(const string&)’ {aka ‘digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)’} to ‘std::vector<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>::value_type’ {aka ‘std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)’} [-fpermissive]
  423 |     m_createList.push_back(&T::createInternal);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           digidoc::Container* (*)(const string&) {aka digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)}
In file included from /usr/include/c++/10/vector:67,
                 from /home/hector/git/libdigidocpp/src/Container.h:26,
                 from /home/hector/git/libdigidocpp/src/Container.cpp:20:
/usr/include/c++/10/bits/stl_vector.h:1203:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&); _Alloc = std::allocator<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)]’ (near match)
 1203 |       push_back(value_type&& __x)
      |       ^~~~~~~~~
/usr/include/c++/10/bits/stl_vector.h:1203:7: note:   conversion of argument 1 would be ill-formed:
/home/hector/git/libdigidocpp/src/Container.cpp:423:27: error: invalid conversion from ‘digidoc::Container* (*)(const string&)’ {aka ‘digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)’} to ‘std::vector<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>::value_type’ {aka ‘std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)’} [-fpermissive]
  423 |     m_createList.push_back(&T::createInternal);
      |     ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      |                           |
      |                           digidoc::Container* (*)(const string&) {aka digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)}
/home/hector/git/libdigidocpp/src/Container.cpp:424:25: error: no matching function for call to ‘push_back(digidoc::Container* (*)(const string&))’
  424 |     m_openList.push_back(&T::openInternal);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/vector:67,
                 from /home/hector/git/libdigidocpp/src/Container.h:26,
                 from /home/hector/git/libdigidocpp/src/Container.cpp:20:
/usr/include/c++/10/bits/stl_vector.h:1187:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&); _Alloc = std::allocator<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)]’ (near match)
 1187 |       push_back(const value_type& __x)
      |       ^~~~~~~~~
/usr/include/c++/10/bits/stl_vector.h:1187:7: note:   conversion of argument 1 would be ill-formed:
/home/hector/git/libdigidocpp/src/Container.cpp:424:25: error: invalid conversion from ‘digidoc::Container* (*)(const string&)’ {aka ‘digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)’} to ‘std::vector<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>::value_type’ {aka ‘std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)’} [-fpermissive]
  424 |     m_openList.push_back(&T::openInternal);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
      |                         |
      |                         digidoc::Container* (*)(const string&) {aka digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)}
In file included from /usr/include/c++/10/vector:67,
                 from /home/hector/git/libdigidocpp/src/Container.h:26,
                 from /home/hector/git/libdigidocpp/src/Container.cpp:20:
/usr/include/c++/10/bits/stl_vector.h:1203:7: note: candidate: ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&); _Alloc = std::allocator<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>; std::vector<_Tp, _Alloc>::value_type = std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)]’ (near match)
 1203 |       push_back(value_type&& __x)
      |       ^~~~~~~~~
/usr/include/c++/10/bits/stl_vector.h:1203:7: note:   conversion of argument 1 would be ill-formed:
/home/hector/git/libdigidocpp/src/Container.cpp:424:25: error: invalid conversion from ‘digidoc::Container* (*)(const string&)’ {aka ‘digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)’} to ‘std::vector<std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)>::value_type’ {aka ‘std::unique_ptr<digidoc::Container> (*)(const std::__cxx11::basic_string<char>&)’} [-fpermissive]
  424 |     m_openList.push_back(&T::openInternal);
      |     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
      |                         |
      |                         digidoc::Container* (*)(const string&) {aka digidoc::Container* (*)(const std::__cxx11::basic_string<char>&)}
make[2]: *** [src/CMakeFiles/digidocpp.dir/build.make:194: src/CMakeFiles/digidocpp.dir/Container.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:222: src/CMakeFiles/digidocpp.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

### PR DESCRIPTION
**Pull request by metsma**
Fixes #371

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by hsanjuan** [comment]
Errors have been reduced but still a couple of renames are missing:

```
/home/hector/git/libdigidocpp/src/Container.cpp: In instantiation of ‘static void digidoc::Container::addContainerImplementation() [with T = digidoc::PDF]’:
/home/hector/git/libdigidocpp/src/Container.cpp:158:48:   required from here
/home/hector/git/libdigidocpp/src/Container.cpp:423:28: error: ‘createInternal’ is not a member of ‘digidoc::PDF’
  423 |     m_createList.push_back(&T::createInternal);
      |                            ^~~~~~~~~~~~~~~~~~
/home/hector/git/libdigidocpp/src/Container.cpp:424:26: error: ‘openInternal’ is not a member of ‘digidoc::PDF’
  424 |     m_openList.push_back(&T::openInternal);
      |                          ^~~~~~~~~~~~~~~~
```

**Comment by hsanjuan** [comment]
After renaming those I also get:

```
/home/hector/git/libdigidocpp/src/PDF.cpp:48:1: error: expected class-name before ‘{’ token
   48 | {
      | ^
/home/hector/git/libdigidocpp/src/PDF.cpp: In constructor ‘digidoc::DSSPdfSigIncMemDocument::DSSPdfSigIncMemDocument(const char*)’:
/home/hector/git/libdigidocpp/src/PDF.cpp:50:58: error: class ‘digidoc::DSSPdfSigIncMemDocument’ does not have any field named ‘PdfSigIncMemDocument’
   50 |     DSSPdfSigIncMemDocument(const char* pszInpFilename): PdfSigIncMemDocument(pszInpFilename) {}
      |                                                          ^~~~~~~~~~~~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp: In member function ‘PoDoFo::PdfAcroForm* digidoc::DSSPdfSigIncMemDocument::GetAcroForm()’:
/home/hector/git/libdigidocpp/src/PDF.cpp:51:41: error: ‘GetExistedAcroForm’ was not declared in this scope
   51 |     PdfAcroForm* GetAcroForm() { return GetExistedAcroForm(nullptr); }
      |                                         ^~~~~~~~~~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp: At global scope:
/home/hector/git/libdigidocpp/src/PDF.cpp:173:6: error: no declaration matches ‘void digidoc::PDF::addDataFile(std::istream*, const string&, const string&)’
  173 | void PDF::addDataFile(istream * /*is*/, const string & /*fileName*/, const string & /*mediaType*/)
      |      ^~~
In file included from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/home/hector/git/libdigidocpp/src/PDF.h:38:10: note: candidates are: ‘virtual void digidoc::PDF::addDataFile(std::unique_ptr<std::basic_istream<char> >, const string&, const string&)’
   38 |     void addDataFile(std::unique_ptr<std::istream> is, const std::string &fileName, const std::string &mediaType) override;
      |          ^~~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:168:6: note:                 ‘virtual void digidoc::PDF::addDataFile(const string&, const string&)’
  168 | void PDF::addDataFile(const string & /*path*/, const string & /*mediaType*/)
      |      ^~~
In file included from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/home/hector/git/libdigidocpp/src/PDF.h:30:7: note: ‘class digidoc::PDF’ defined here
   30 | class PDF: public Container
      |       ^~~
/home/hector/git/libdigidocpp/src/PDF.cpp:183:12: error: no declaration matches ‘digidoc::Container* digidoc::PDF::createInternal(const string&)’
  183 | Container* PDF::createInternal(const string & /*unused*/)
      |            ^~~
/home/hector/git/libdigidocpp/src/PDF.cpp:183:12: note: no functions named ‘digidoc::Container* digidoc::PDF::createInternal(const string&)’
In file included from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/home/hector/git/libdigidocpp/src/PDF.h:30:7: note: ‘class digidoc::PDF’ defined here
   30 | class PDF: public Container
      |       ^~~
/home/hector/git/libdigidocpp/src/PDF.cpp:198:12: error: no declaration matches ‘digidoc::Container* digidoc::PDF::openInternal(const string&)’
  198 | Container* PDF::openInternal(const string &path)
      |            ^~~
/home/hector/git/libdigidocpp/src/PDF.cpp:198:12: note: no functions named ‘digidoc::Container* digidoc::PDF::openInternal(const string&)’
In file included from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/home/hector/git/libdigidocpp/src/PDF.h:30:7: note: ‘class digidoc::PDF’ defined here
   30 | class PDF: public Container
      |       ^~~
/home/hector/git/libdigidocpp/src/PDF.cpp: In member function ‘virtual digidoc::Signature* digidoc::PDF::sign(digidoc::Signer*)’:
/home/hector/git/libdigidocpp/src/PDF.cpp:329:13: error: ‘class digidoc::DSSPdfSigIncMemDocument’ has no member named ‘GetSignatureField’
  329 |         doc.GetSignatureField()->SetSignatureDate(PdfDate());
      |             ^~~~~~~~~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:330:13: error: ‘class digidoc::DSSPdfSigIncMemDocument’ has no member named ‘GetSignatureField’
  330 |         doc.GetSignatureField()->SetSignatureReason(roles);
      |             ^~~~~~~~~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:331:13: error: ‘class digidoc::DSSPdfSigIncMemDocument’ has no member named ‘Initialize’
  331 |         doc.Initialize();
      |             ^~~~~~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:359:13: error: ‘class digidoc::DSSPdfSigIncMemDocument’ has no member named ‘Write’
  359 |         doc.Write(&out);
      |             ^~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:381:90: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<std::basic_istream<char> >’ and ‘std::shared_ptr<std::__cxx11::basic_stringstream<char> >’)
  381 |         dataFile->m_is = make_shared<stringstream>(string(buf.GetBuffer(), buf.GetSize()));
      |                                                                                          ^
In file included from /usr/include/c++/10/memory:83,
                 from /home/hector/git/libdigidocpp/src/Container.h:24,
                 from /home/hector/git/libdigidocpp/src/PDF.h:22,
                 from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/usr/include/c++/10/bits/unique_ptr.h:371:19: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = std::basic_istream<char>; _Dp = std::default_delete<std::basic_istream<char> >]’
  371 |       unique_ptr& operator=(unique_ptr&&) = default;
      |                   ^~~~~~~~
/usr/include/c++/10/bits/unique_ptr.h:371:29: note:   no known conversion for argument 1 from ‘std::shared_ptr<std::__cxx11::basic_stringstream<char> >’ to ‘std::unique_ptr<std::basic_istream<char> >&&’
  371 |       unique_ptr& operator=(unique_ptr&&) = default;
      |                             ^~~~~~~~~~~~
/usr/include/c++/10/bits/unique_ptr.h:386:2: note: candidate: ‘template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::__uniq_ptr_impl<_Tp, _Dp>::pointer>, std::__not_<std::is_array<_Up> > >, std::is_assignable<_T2&, _U2&&> >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Up = _Up; _Ep = _Ep; _Tp = std::basic_istream<char>; _Dp = std::default_delete<std::basic_istream<char> >]’
  386 |  operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
      |  ^~~~~~~~
/usr/include/c++/10/bits/unique_ptr.h:386:2: note:   template argument deduction/substitution failed:
/home/hector/git/libdigidocpp/src/PDF.cpp:381:90: note:   ‘std::shared_ptr<std::__cxx11::basic_stringstream<char> >’ is not derived from ‘std::unique_ptr<_Tp, _Dp>’
  381 |         dataFile->m_is = make_shared<stringstream>(string(buf.GetBuffer(), buf.GetSize()));
      |                                                                                          ^
In file included from /usr/include/c++/10/memory:83,
                 from /home/hector/git/libdigidocpp/src/Container.h:24,
                 from /home/hector/git/libdigidocpp/src/PDF.h:22,
                 from /home/hector/git/libdigidocpp/src/PDF.cpp:20:
/usr/include/c++/10/bits/unique_ptr.h:395:7: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = std::basic_istream<char>; _Dp = std::default_delete<std::basic_istream<char> >; std::nullptr_t = std::nullptr_t]’
  395 |       operator=(nullptr_t) noexcept
      |       ^~~~~~~~
/usr/include/c++/10/bits/unique_ptr.h:395:17: note:   no known conversion for argument 1 from ‘std::shared_ptr<std::__cxx11::basic_stringstream<char> >’ to ‘std::nullptr_t’
  395 |       operator=(nullptr_t) noexcept
      |                 ^~~~~~~~~
In file included from /home/hector/git/libdigidocpp/src/PDF.cpp:24:
/home/hector/git/libdigidocpp/src/PDF.cpp:389:21: error: ‘EXCEPTION’ was not declared in this scope; did you mean ‘EXCEPTION_ADD’?
  389 |         THROW_CAUSE(EXCEPTION(e.what()), "Failed to sign PDF.");
      |                     ^~~~~~~~~
/home/hector/git/libdigidocpp/src/log.h:63:81: note: in definition of macro ‘THROW_CAUSE’
   63 | #define THROW_CAUSE(_cause, ...) throw Exception(EXCEPTION_PARAMS(__VA_ARGS__), _cause)
      |                                                                                 ^~~~~~
/home/hector/git/libdigidocpp/src/PDF.cpp:391:1: warning: control reaches end of non-void function [-Wreturn-type]
  391 | }
      | ^
```

**Comment by metsma** [comment]
updated PR.
PdfSigIncMemDocument I think you have recent PoDoFo and this code is not ported to this version

**Comment by hsanjuan** [comment]
https://github.com/open-eid/libdigidocpp/pull/372#issuecomment-712618717 still persists.

I fix it with 

```diff
diff --git a/src/Container.cpp b/src/Container.cpp
index 0ef7ba0..3decc43 100644
--- a/src/Container.cpp
+++ b/src/Container.cpp
@@ -420,8 +420,8 @@ unique_ptr<Container> Container::openPtr(const string &path)
 template<class T>
 void Container::addContainerImplementation()
 {
-    m_createList.push_back(&T::createInternal);
-    m_openList.push_back(&T::openInternal);
+    m_createList.push_back(&T::createPtr);
+    m_openList.push_back(&T::openPtr);
 }
```



> PdfSigIncMemDocument I think you have recent PoDoFo and this code is not ported to this version

libpodofo-devel-0.9.6-4.8.x86_64

**Comment by metsma** [comment]
Nice catch I wonder that none other compiler complains of this.
I think PoDoFo 0.9.4 is last version that I tested

**Comment by hsanjuan** [comment]
I have `gcc version 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c] (SUSE Linux)`.

This does not look like a dependency problem though, but a syntax one:

```
/home/hector/git/libdigidocpp/src/PDF.cpp:48:1: error: expected class-name before ‘{’ token
   48 | {
      | ^
```

**Comment by metsma** [comment]
```
class DSSPdfSigIncMemDocument: public PdfSigIncMemDocument
{
```
I cannot see problem here.
Can you grep header for class PdfSigIncMemDocument

**Comment by hsanjuan** [comment]
*sighs* https://sourceforge.net/p/podofo/code/1790/

**Pull request merged**
