### PR TITLE
add missing compile time dependencies

### PR DESCRIPTION
**Pull request by colourful-land**

### CODE REVIEW

**Comment by metsma** [comment]
doxygen swig and boost are optional requirements

**Comment by metsma** [comment]
Why you duplicate the libxml-security-c-dev libxerces-c-dev xsdcxx packages?

**Comment by colourful-land** [comment]
metsma: thanks for taking a look. I duplicated it because it was midnight and my brain is dead. Sorry.

**Comment by colourful-land** [comment]
The mistake is corrected metsma:)

**Comment by metsma** [comment]
libxml-security-c-dev depends already libxerces-c-dev
https://packages.ubuntu.com/trusty/libxml-security-c-dev

swig is unused on linux
libboost-dev is optional for unittests like doxygen for api docs

**Comment by colourful-land** [comment]
You are right. I took a Call Stack as a failure, in fact it's part of a Warning. The tool builds fine without clearing out the complaints.
~~~
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  test/CMakeLists.txt:1 (find_package)
~~~~

**Pull request closed without merging**
