### PR TITLE
add missing libboost-dev dependency

### PR DESCRIPTION
**Pull request by vti**

### CODE REVIEW

**Comment by metsma** [comment]
Can you please change it to libboost-test-dev and mention that it is optional dependency for unit testing

**Comment by vti** [comment]
Actually I wasn't building and/or running tests. Or is it building dev version by default?

**Comment by metsma** [comment]
it is build time optional requirement for running untittests

**Comment by vti** [comment]
So how to build the prod version?

**Comment by metsma** [comment]
you can ignore the missing boost cmake warning

**Comment by vti** [comment]
Ah, I see. That's a warning, not an error.

**Pull request closed without merging**
