### PR TITLE
Compatibility with Latvian ASiC-E documents

### PR DESCRIPTION
**Pull request by metsma**
removed "TimeStamp have to be after OCSP response" condition on validation
removed "TimeStamp time and OCSP producedAt have to be within 24h" condition on validation
(security risks raised as the Estonian eID certificates' validity can be suspended temporarily and activated later additional analysis recomended)

SKEID-93

Signed-off-by: Raul Metsma raul@metsma.ee

Recreated open-eid/libdigidocpp#10

### CODE REVIEW

**Comment by metsma** [comment]
"TimeStamp MUST be after OCSP" Can you point to any reference to this claim?

**Comment by user8547** [comment]
This technical requirement comes from legal requirement set by eIDAS art 32 that validation of QES should confirm that at the time of signing the qualified certificate was valid.

If the OCSP is obtained before the signing (timestamping) the OCSP response obviously does not guarantee that at the time of signing the certificate was still valid.

**Comment by metsma** [comment]
Before you said "TimeStamp MUST be after OCSP" and now 
"If the OCSP is obtained before the signing (timestamping) the OCSP response obviously does not guarantee that at the time of signing the certificate was still valid."
And lets not forget OCSP responses have nextUpdate flag. Even when we take OCSP response we cannot be sure that certificate isn't revoked when timestamp is taken.
What this commit does, OCSP response should be fresh enough compared timestamp.

**Comment by user8547** [comment]
I updated my comment. There was typo in your commit message, that's the reason.

**Comment by metsma** [comment]
And how to be sure that certificate was not suspended when timestamp was taken and later OCSP status with GOOD status added?
Anyway this is not github ticket discussion and you can contact software owner info@ria.ee

**Comment by user8547** [comment]
"And how to be sure that certificate was not suspended when timestamp was taken and later OCSP status with GOOD status added?"

The answer is that you cannot. But that's a different issue that has to be solved.

Changes like this which make an invalid signature valid (or vice versa) should not go in without technical standard being updated accordingly. This git libdigidoccpp behaviour is not compatible with digidoc4j and http://open-eid.github.io/SiVa/siva/appendix/validation_policy/.

**Comment by metsma** [comment]
As far i know, SiVa uses digidoc4j backend and digidoc4j (based DDS) does not give error on this file.
DDS https://github.com/esig/dss is developed by EU commission

**Pull request merged**
