### PR TITLE
Remove non-free files and files with questionable terms

### PR DESCRIPTION
**Pull request by andrewshadura**
The text of RFC 3161 isn't licensed under a free software license.
The text of .ZIP File Format Specification prohibits its distribution
without a prior written permission.
ETSI standards texts prohibit reproduction without a prior written
permission.

See https://wiki.debian.org/NonFreeIETFDocuments and http://josefsson.org/bcp78broken/ for details regarding RFCs.

It is better to not redistribute these files, not store them in Git repository and not include them into the release tarballs.

### CODE REVIEW

**Comment by martinpaljak** [comment]
The thing to do here is to make sure that *source* distributions (or, more precisely, Debian packages?) don't include anything that might be "questionable" but IMHO common sense suggests things that are logically combined with the project and freely available and help any developer (instead of being enforced to locate something from the internet) and distributed unmodified should belong to the repository, until requested to be removed by some offended rights owner.

**Comment by martinpaljak** [comment]
Thus changes that address the problem via source distribution changes or packaging changes would be OK but I don't think that reaping out docs without an alternative would help. Maybe reducing the repository size and have links (if all documents are linkable) instead in the README?

**Comment by andrewshadura** [comment]
Well, this is the problem that the licensing terms of these documents do not allow them to be distributed. Yes, adding links to them may be a good alternative, but they shouldn't be in the source in the first place.

**Comment by andrewshadura** [comment]
@martinpaljak, one more question: what are the distribution terms for BDOC standards? I can't find them anywhere.

**Comment by metsma** [comment]
Removed files and added online refereneces to documentation

**Pull request closed without merging**
